$Merge(1( Welcome to $Talker-Name ) 2($Line_fill(=)))

 $Talker-Name is here for one and all as a place to just relax
and chat.
 Look around and enjoy yourself. If you find that you like it
and would like a Permanent Account, then just ask one of our
SuperUsers for "^BResidency^b".  If you don't know who they are,
just ask another user, or type: "^Blsu^b".
 Getting ^BResidency^b will give you access to some more
advanced features, and you will get all your information
saved between visits. This is password protected.
 To get more information on how to use $Talker-Name, just
type: "^Bhelp^s" once you are online.

$Line_fill(-)
