
# End of auto generated bit...
CC = $(AC_CC)

CONFIGS  = -DROOT=\"$(ROOTDIR)/\" -DVERSION=\"$(VERSIONID)\" $(TOTAL-DEFINES) \
           $(PATHS) -D_GNU_SOURCE
CFLAGS   =  $(WARNS) -I$(IDIR) -I- $(CONFIGS) $(XTRA_GCC_OPTS) -DSHOW_WHY_DIED
LDFLAGS  =  $(LIBS) $(AC_LIBS)

OFILES := $(patsubst $(IDIR)/%.c,$(IDIR)/%.o,$(wildcard $(IDIR)/*.c))
TEST_FILES := $(patsubst $(IDIR)/tmp/%.c,$(IDIR)/tmp/%,$(wildcard $(IDIR)/tmp/*.c))

all: $(OFILES)
		@echo ""
		@echo "Linking intercom"
		@echo ""
		@$(CC) $(CFLAGS) $(LDFLAGS) -o $(IDIR)/intercom \
		  $(OFILES) $(LDFLAGS)

$(IDIR)/%.o: $(IDIR)/%.c
		@echo " Compiling $*..."
		@$(CC) $(CFLAGS) -c $< -o $@

install: all
		-@mv -f $(IBIN_INSTALL) $(IBIN_OLD_INSTALL).$(DATE)
		@mv $(IBIN) $(IBIN_INSTALL)
		@chmod $(EXECMOD) $(IBIN_INSTALL)

$(IDIR)/tmp/test%: $(IDIR)/tmp/test%.c $(OFILES)
		@echo " Compiling test: $*..."
		@$(CC) $(CFLAGS) -c $< -o $@
		@echo "Linking test: $*"
		@$(CC) $(CFLAGS) $(LDFLAGS) -o $@ \
		  assert_loop.o tools.o fix.o socket_com.o socket_com_q.o socket_poll.o timer_q.o $< $(LDFLAGS)

test: $(TEST_FILES)

tags:
		@etags $(IDIR)/*.c $(IDIR)/*.h

clean:
		rm -f $(IDIR)/*.o $(IDIR)/intercom $(IDIR)/test TAGS \
		  $(IDIR)/*.bb $(IDIR)/*.bbg $(IDIR)/*.da \
		  $(IDIR)/tmp/*.o $(IDIR)/tmp/test? $(IDIR)/tmp/test1?

distclean: clean
		rm -f Makefile

showcomp:
		@echo $(CC) $(CFLAGS) $(DEFS) OBJS: $(OFILES)
