#ifndef TALKER_MAIN_H
#define TALKER_MAIN_H

#define TWOCAN_CODE 1 /* so people can try and write "portable" code for EW */

#include "autoconf.h"

#include "main_system.h"

#include "no_stack_here.h" /* I'm facist .. but so what */

#include "config.h"

#define FIX_NAMESPACE_SYMBOL twocan_autoconf_

#define USE_TERMCAP 1

#include "fix.h"


/* goes first in case they want to override things... */
#include "local_talker.h"


/* **** structures etc. **** */

/* these need to be in this order... or some of them do anyway... *sigh* */
#include "assert_loop.h"
#include "tools.h"

#include "alias.h"
#include "boot.h"
#include "games.h"
#include "timer.h"
#include "last_command.h"
#include "lists.h"
#include "mode.h"
#include "process_output.h"
#include "process_input.h"
#include "structs.h"
#include "load_player.h"
#include "save_player.h"
#include "player_linked_list.h"
#include "get_parameter.h"
#include "socket.h"
#include "colourise.h"
#include "terminal.h"
#include "prompt.h"
#include "hangman.h"
#include "player.h"

#include "news.h"
#include "room.h"

#include "auth_player.h"
#include "autoexec.h"
#include "angel.h"
#include "buffers.h"
#include "channels.h"
#include "check_receive.h"
#include "child_com.h"
#include "cmds_list.h"
#include "construct_names.h"
#include "crazynews.h"
#include "disk.h"
#include "display_time.h"
#include "dl_load.h"
#include "dns.h"
#include "draughts.h"
#include "editor.h"
#include "email.h"
#include "familiars.h"
#include "idle.h"
#include "karma.h"
#include "last_logon.h"
#include "log.h"
#include "logoff.h"
#include "logon.h"
#include "mail.h"
#include "mask_coms.h"
#include "multi_base.h"
#include "msgs.h"
#include "match.h"
#include "nickname.h"
#include "nuke.h"
#include "output_compress.h"
#include "pager.h"
#include "player_event.h"
#include "player_find.h"
#include "player_tree.h"
#include "help.h"
#include "privs.h"
#include "priv_test.h"
#include "safemalloc.h"
#include "schedule.h"
#include "shutdown.h"
#include "session.h"
#include "socials.h"
#include "spodlist.h"
#include "sps.h"
#include "stats_files.h"
#include "system.h"
#include "text_objs.h"
#include "tip.h"
#include "trace.h"
#include "ttt.h"
#include "version.h"
#include "word_number.h"
#include "word_time.h"
#include "wotw.h"

#include "user_configure.h"



/* **** extern declarations **** */

#include "extern-admin.h"
#include "extern-alarm.h"
#include "extern-alias.h"
#include "extern-angel.h"
#include "extern-auth_player.h"
#include "extern-autoexec.h"
#include "extern-assert_loop.h"
#include "extern-backups.h"
#include "extern-blank.h"
#include "extern-boot.h"
#include "extern-buffers.h"
#include "extern-channels.h"
#include "extern-check.h"
#include "extern-check_receive.h"
#include "extern-child_com.h"
#include "extern-chlim.h"
#include "extern-cmd_line.h"
#include "extern-cmds_list.h"
#include "extern-colourise.h"
#include "extern-commands.h"
#include "extern-communication.h"
#include "extern-construct_names.h"
#include "extern-converse.h"
#include "extern-copy_str.h"
#include "extern-crazynews.h"
#include "extern-disk.h"
#include "extern-display_time.h"
#include "extern-dl_load.h"
#include "extern-dns.h"
#include "extern-draughts.h"
#include "extern-editor.h"
#include "extern-email.h"
#include "extern-familiars.h"
#include "extern-friend_communication.h"
#include "extern-jotd.h"
#include "extern-games.h"
#include "extern-get_parameter.h"
#include "extern-glue_intercom.h"
#include "extern-hangman.h"
#include "extern-help.h"
#include "extern-idle.h"
#include "extern-karma.h"
#include "extern-last_command.h"
#include "extern-last_logon.h"
#include "extern-lists.h"
#include "extern-load_player.h"
#include "extern-log.h"
#include "extern-logoff.h"
#include "extern-logon.h"
#include "extern-mail.h"
#include "extern-marriage.h"
#include "extern-mask_coms.h"
#include "extern-match.h"
#include "extern-mode.h"
#include "extern-motd.h"
#include "extern-multi_base.h"
#include "extern-multi_communication.h"
#include "extern-msgs.h"
#include "extern-news.h"
#include "extern-nickname.h"
#include "extern-nuke.h"
#include "extern-output_compress.h"
#include "extern-pager.h"
#include "extern-passwd.h"
#include "extern-player_event.h"
#include "extern-player_find.h"
#include "extern-player_linked_list.h"
#include "extern-player_tree.h"
#include "extern-privs.h"
#include "extern-priv_test.h"
#include "extern-process_input.h"
#include "extern-process_output.h"
#include "extern-prompt.h"
#include "extern-quit_in.h"
#include "extern-room.h"
#include "extern-safemalloc.h"
#include "extern-save_player.h"
#include "extern-schedule.h"
#include "extern-screenlock.h"
#include "extern-session.h"
#include "extern-shutdown.h"
#include "extern-signal.h"
#include "extern-socials.h"
#include "extern-socket.h"
#include "extern-show.h"
#include "extern-spodlist.h"
#include "extern-sps.h"
#include "extern-sumotd.h"
#include "extern-super_channel.h"
#include "extern-stats_files.h"
#include "extern-system.h"
#include "extern-sys_rlim.h"
#include "extern-terminal.h"
#include "extern-text_objs.h"
#include "extern-timer.h"
#include "extern-timer_player.h"
#include "extern-tip.h"
#include "extern-toggle.h"
#include "extern-tools.h"
#include "extern-trace.h"
#include "extern-ttt.h"
#include "extern-user_configure.h"
#include "extern-who.h"
#include "extern-word_number.h"
#include "extern-word_time.h"
#include "extern-wotw.h"

/* goes last... */
#include "extern-local_talker.h"


#endif
