#ifndef MODE_H
#define MODE_H

#define MODE_MODES_SZ 8

#define MODE_ID_ERROR 0

#define MODE_ID_BASE_EW 1
#define MODE_ID_BASE_NUTS 2
#define MODE_ID_BASE_IRC 3

#define MODE_ID_REAL_OFFSET 3

#define MODE_ID_MAIL (MODE_ID_REAL_OFFSET + 1)
#define MODE_ID_NEWS (MODE_ID_REAL_OFFSET + 2)
#define MODE_ID_NEWSGROUP (MODE_ID_REAL_OFFSET + 3)
#define MODE_ID_ROOM (MODE_ID_REAL_OFFSET + 4)
#define MODE_ID_DRAUGHTS (MODE_ID_REAL_OFFSET + 5)
#define MODE_ID_EDIT (MODE_ID_REAL_OFFSET + 6)
#define MODE_ID_STATS (MODE_ID_REAL_OFFSET + 7)
#define MODE_ID_CHECK (MODE_ID_REAL_OFFSET + 8)
#define MODE_ID_CONVERSE (MODE_ID_REAL_OFFSET + 9)
#define MODE_ID_INTERCOM (MODE_ID_REAL_OFFSET + 10)
#define MODE_ID_CHLIM (MODE_ID_REAL_OFFSET + 11)
#define MODE_ID_CHANNELS (MODE_ID_REAL_OFFSET + 12)
#define MODE_ID_CONFIGURE (MODE_ID_REAL_OFFSET + 13)

#define MODE_ID_REAL_NON_LEAVE_OFFSET (MODE_ID_REAL_OFFSET + 13)

#define MODE_ID_PAGER (MODE_ID_REAL_NON_LEAVE_OFFSET + 1)
#define MODE_ID_RES_1 (MODE_ID_REAL_NON_LEAVE_OFFSET + 2)
#define MODE_ID_RES_2 (MODE_ID_REAL_NON_LEAVE_OFFSET + 3)
#define MODE_ID_RES_3 (MODE_ID_REAL_NON_LEAVE_OFFSET + 4)
#define MODE_ID_JAIL (MODE_ID_REAL_NON_LEAVE_OFFSET + 5)
#define MODE_ID_LOGON_NAME (MODE_ID_REAL_NON_LEAVE_OFFSET + 6)
#define MODE_ID_LOGON_PASSWD_1 (MODE_ID_REAL_NON_LEAVE_OFFSET + 7)
#define MODE_ID_LOGON_PASSWD_2 (MODE_ID_REAL_NON_LEAVE_OFFSET + 8)
#define MODE_ID_LOGON_PASSWD_3 (MODE_ID_REAL_NON_LEAVE_OFFSET + 9)
#define MODE_ID_LOGON_PASSWD_4 (MODE_ID_REAL_NON_LEAVE_OFFSET + 10)
#define MODE_ID_LOGON_NEWBIE_1 (MODE_ID_REAL_NON_LEAVE_OFFSET + 11)
#define MODE_ID_LOGON_NEWBIE_2 (MODE_ID_REAL_NON_LEAVE_OFFSET + 12)
#define MODE_ID_LOGON_NEWBIE_3 (MODE_ID_REAL_NON_LEAVE_OFFSET + 13)
#define MODE_ID_LOGON_NEWBIE_4 (MODE_ID_REAL_NON_LEAVE_OFFSET + 14)
#define MODE_ID_LOGON_NEWBIE_5 (MODE_ID_REAL_NON_LEAVE_OFFSET + 15)
#define MODE_ID_LOGON_NEWBIE_6 (MODE_ID_REAL_NON_LEAVE_OFFSET + 16)
#define MODE_ID_LOGON_DISCLAIMER (MODE_ID_REAL_NON_LEAVE_OFFSET + 17)
#define MODE_ID_LOGON_FINISH (MODE_ID_REAL_NON_LEAVE_OFFSET + 18)
#define MODE_ID_LOGON_MOTD (MODE_ID_REAL_NON_LEAVE_OFFSET + 19)
#define MODE_ID_LOGON_SUMOTD (MODE_ID_REAL_NON_LEAVE_OFFSET + 20)
#define MODE_ID_MAIL_1 (MODE_ID_REAL_NON_LEAVE_OFFSET + 21)
#define MODE_ID_MAIL_2 (MODE_ID_REAL_NON_LEAVE_OFFSET + 22)
#define MODE_ID_MAIL_3 (MODE_ID_REAL_NON_LEAVE_OFFSET + 23)
#define MODE_ID_PASSWD_1 (MODE_ID_REAL_NON_LEAVE_OFFSET + 24)
#define MODE_ID_PASSWD_2 (MODE_ID_REAL_NON_LEAVE_OFFSET + 25)
#define MODE_ID_PASSWD_3 (MODE_ID_REAL_NON_LEAVE_OFFSET + 26)
#define MODE_ID_SCREENLOCK (MODE_ID_REAL_NON_LEAVE_OFFSET + 27)

#define MODE_ID_SZ (1 + (MODE_ID_REAL_NON_LEAVE_OFFSET + 27))

#define MODE_FLAGS_DEFAULT 0
#define MODE_FLAGS_SYSTEM_INFO_ONLY (1<<0)

/* generic_mode needs to go in player.h due to the way the referencing works */
typedef struct generic_mode generic_mode;

#endif
