#ifndef OUTPUT_COMPRESS_H
#define OUTPUT_COMPRESS_H

#define OUTPUT_COMPRESS_BUF_SZ 1024

/* Z_NO_COMPRESSION (0), Z_BEST_SPEED (1), Z_BEST_COMPRESSION (9) */
#define OUTPUT_COMPRESS_LEVEL Z_BEST_COMPRESSION

#endif
