#ifndef WORD_TIME_H
#define WORD_TIME_H

#ifdef WORD_TIME_C

# define WORD_TIME_DIV_YEARS   (60 * 60 * 24 * 365)
# define WORD_TIME_DIV_WEEKS   (60 * 60 * 24 * 7)
# define WORD_TIME_DIV_DAYS    (60 * 60 * 24)
# define WORD_TIME_DIV_HOURS   (60 * 60)
# define WORD_TIME_DIV_MINUTES (60)
# define WORD_TIME_DIV_SECONDS (1)

#endif

#define WORD_TIME_YEARS (1<<0)
#define WORD_TIME_WEEKS (1<<1)
#define WORD_TIME_DAYS (1<<2)
#define WORD_TIME_HOURS (1<<3)
#define WORD_TIME_MINUTES (1<<4)
#define WORD_TIME_SECONDS (1<<5)
#define WORD_TIME_MOD_YEARS (0) /* doesn't do anything as year is biggest */
#define WORD_TIME_MOD_WEEKS (1<<6)
#define WORD_TIME_MOD_DAYS (1<<7)
#define WORD_TIME_MOD_HOURS (1<<8)
#define WORD_TIME_MOD_MINUTES (1<<9)
#define WORD_TIME_MOD_SECONDS (1<<10)
#define WORD_TIME_STICK_YEARS (1<<11)
#define WORD_TIME_STICK_WEEKS (1<<12)
#define WORD_TIME_STICK_DAYS (1<<13)
#define WORD_TIME_STICK_HOURS (1<<14)
#define WORD_TIME_STICK_MINUTES (1<<15)
#define WORD_TIME_STICK_SECONDS (1<<16)

#define WORD_TIME_NOT_USED ((1<<17) | (1<<18) | (1<<19) | (1<<20) | (1<<21) | (1<<22) | (1<<23) | (1<<24) | (1<<25) | (1<<26) | (1<<27) | (1<<28) | (1<<29) | (1<<30) | (1<<31))

#define WORD_TIME_ALL (WORD_TIME_SECONDS | WORD_TIME_MINUTES | WORD_TIME_HOURS | WORD_TIME_DAYS | WORD_TIME_WEEKS | WORD_TIME_YEARS)

#define WORD_TIME_DEFAULT (WORD_TIME_SECONDS | WORD_TIME_MINUTES | WORD_TIME_HOURS | WORD_TIME_DAYS)

#define WORD_TIME_MOD_ALL (WORD_TIME_MOD_YEARS | WORD_TIME_MOD_WEEKS | WORD_TIME_MOD_DAYS | WORD_TIME_MOD_HOURS | WORD_TIME_MOD_MINUTES | WORD_TIME_MOD_SECONDS)

#define WORD_TIME_STICK_ALL (WORD_TIME_STICK_YEARS | WORD_TIME_STICK_WEEKS | WORD_TIME_STICK_DAYS | WORD_TIME_STICK_HOURS | WORD_TIME_STICK_MINUTES | WORD_TIME_STICK_SECONDS)


#define WORD_TIME_PARSE_DEFAULT (0)
#define WORD_TIME_PARSE_ERRORS (1<<0)
#define WORD_TIME_PARSE_DEF_YEARS (1<<1) /* higher overrides smaller */
#define WORD_TIME_PARSE_DEF_WEEKS (1<<2)
#define WORD_TIME_PARSE_DEF_DAYS (1<<3)
#define WORD_TIME_PARSE_DEF_HOURS (1<<4)
#define WORD_TIME_PARSE_DEF_MINUTES (1<<5)
#define WORD_TIME_PARSE_DEF_SECONDS (1<<6)

#endif
