#ifndef WORD_NUMBER_H
#define WORD_NUMBER_H

#define WORD_NUMBER_WORDS_SZ 33

#define WORD_NUMBER_ZERO 0
#define WORD_NUMBER_ONE 1
#define WORD_NUMBER_TWO 2
#define WORD_NUMBER_THREE 3
#define WORD_NUMBER_FOUR 4
#define WORD_NUMBER_FIVE 5
#define WORD_NUMBER_SIX 6
#define WORD_NUMBER_SEVEN 7
#define WORD_NUMBER_EIGHT 8
#define WORD_NUMBER_NINE 9
#define WORD_NUMBER_TEN 10
#define WORD_NUMBER_ELEVEN 11
#define WORD_NUMBER_TWELVE 12
#define WORD_NUMBER_THIRTEEN 13
#define WORD_NUMBER_FOURTEEN 14
#define WORD_NUMBER_FIFTEEN 15
#define WORD_NUMBER_SIXTEEN 16
#define WORD_NUMBER_SEVENTEEN 17
#define WORD_NUMBER_EIGHTEEN 18
#define WORD_NUMBER_NINETEEN 19
#define WORD_NUMBER_TWENTY 20
#define WORD_NUMBER_THIRTY 21
#define WORD_NUMBER_FORTY 22
#define WORD_NUMBER_FIFTY 23
#define WORD_NUMBER_SIXTY 24
#define WORD_NUMBER_SEVENTY 25
#define WORD_NUMBER_EIGHTY 26
#define WORD_NUMBER_NINTY 27
#define WORD_NUMBER_HUNDRED 28
#define WORD_NUMBER_THOUSAND 29
#define WORD_NUMBER_MILLION 30
#define WORD_NUMBER_BILLION 31 /* american version */
#define WORD_NUMBER_NEGATIVE 32

#endif
